// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"learn_go/webook/internal/repository"
	"learn_go/webook/internal/repository/article"
	"learn_go/webook/internal/repository/cache"
	"learn_go/webook/internal/repository/dao"
	"learn_go/webook/internal/service"
	"learn_go/webook/internal/web"
	"learn_go/webook/ioc"
)

// Injectors from wire.go:

func InitArticleHandler() *web.ArticleHandler {
	db := NewDB()
	articleDao := dao.NewArticleDao(db)
	articleRepository := article.NewArticleRepository(articleDao)
	authorRepository := article.NewArticleAuthorRepository()
	readerRepository := article.NewArticleReaderRepository()
	loggerV2 := ioc.NewLogger()
	articleService := service.NewArticleService(articleRepository, authorRepository, readerRepository, loggerV2)
	articleHandler := web.NewArticleHandler(articleService, loggerV2)
	return articleHandler
}

func InitArticleHandlerV1() *web.ArticleHandler {
	database := NewMangoDB()
	articleDao := dao.NewMongoArticleDao(database)
	articleRepository := article.NewArticleRepository(articleDao)
	authorRepository := article.NewArticleAuthorRepository()
	readerRepository := article.NewArticleReaderRepository()
	loggerV2 := ioc.NewLogger()
	articleService := service.NewArticleService(articleRepository, authorRepository, readerRepository, loggerV2)
	articleHandler := web.NewArticleHandler(articleService, loggerV2)
	return articleHandler
}

func InitWebServer(templateId string) *gin.Engine {
	cmdable := NewRedis()
	jwtHandler := web.NewJWTHandler(cmdable)
	loggerV2 := ioc.NewLogger()
	v := ioc.InitMiddlewares(jwtHandler, loggerV2)
	smsService := ioc.InitSMSService()
	codeCache := cache.NewCodeCache(cmdable)
	codeRepository := repository.NewCodeRepository(codeCache)
	codeService := service.NewCodeService(templateId, smsService, codeRepository)
	smsHandler := web.NewSMSHandler(codeService)
	db := NewDB()
	userDao := dao.NewUserDao(db)
	userCache := cache.NewUserCache(cmdable)
	userRepository := repository.NewUserRepository(userDao, userCache)
	userService := service.NewUserService(userRepository, loggerV2)
	userHandler := web.NewUserHandler(userService, codeService, jwtHandler)
	oAuth2Service := ioc.InitOAuth2Service()
	oAuth2WechatHandler := web.NewOAuth2WechatHandler(oAuth2Service, userService, jwtHandler)
	testHandler := web.NewTestHandler(loggerV2)
	engine := ioc.InitGin(v, smsHandler, userHandler, oAuth2WechatHandler, testHandler)
	return engine
}

// wire.go:

var (
	providers = wire.NewSet(ioc.NewLogger, NewDB,
		NewRedis, cache.NewCodeCache, cache.NewUserCache, dao.NewUserDao, repository.NewCodeRepository, repository.NewUserRepository, ioc.InitSMSService, ioc.InitOAuth2Service, service.NewCodeService, service.NewUserService, web.NewSMSHandler, web.NewUserHandler, web.NewOAuth2WechatHandler, web.NewJWTHandler, web.NewTestHandler, ioc.InitMiddlewares, ioc.InitGin,
	)

	articleProviders = wire.NewSet(ioc.NewLogger, NewDB,
		NewRedis, web.NewArticleHandler, service.NewArticleService, article.NewArticleRepository, article.NewArticleAuthorRepository, article.NewArticleReaderRepository, dao.NewArticleDao,
	)

	articleProvidersV1 = wire.NewSet(
		NewDB,
		NewRedis,
		NewMangoDB, ioc.NewLogger, web.NewArticleHandler, service.NewArticleService, article.NewArticleRepository, article.NewArticleAuthorRepository, article.NewArticleReaderRepository, dao.NewMongoArticleDao,
	)
)
