apiVersion: v1
kind: Service
metadata:
  name: webook
spec:
  # ClusterIP: 不对外公开
  type: LoadBalancer
  selector:
    app: webook
  ports:
    - protocol: TCP
      # 名字，表示该端口的作用。
      name: http
      # 在集群中公开的访问接口
      port: 4200
      # 要映射的Pod的端口
      targetPort: 8200
